### ISSUE TITLE
Vicuna Benchmark in all 132 languages

### ISSUE THREAD

**Issue by anoopkunchukuttan** [UNHSAILLab/TaCo#1]
Great work! 

I wanted to check if you have created the Vicuna benchmark translated in all 132 languages? If yes, could you please release the same. 

Regards,
Anoop.

**Comment by iBibek** [comment]
Dear @anoopkunchukuttan ,
Thank you :)

Please find the Multilingual Vicuna Benchmark Dataset here: https://huggingface.co/datasets/saillab/taco-datasets/tree/main/multilingual-vicuna-benchmark-dataset

**Comment by anoopkunchukuttan** [comment]
Thank you!
